NUMERIC_FEATURES = [
    "speed",
    "stamina",
    "pace",
    "condition",
    "market_odds",
    "place_odds",
    "carried_weight",
    "horse_weight",
    "horse_weight_diff",
    "distance",
    "age",
    "days_since_last_run",
    "avg_last3_speed",
    "best_time",
    "last600m",
    "jockey_win_rate",
    "trainer_win_rate",
    "horse_recent_win_rate",
    "horse_recent_place_rate",
    "training_score",
    "bloodline_score",
    "odds_rank",
    "odds_delta",
    "ticket_pool_share",
    "draw_bias",
]

CATEGORICAL_FEATURES = [
    "venue",
    "surface",
    "going",
    "weather",
    "sex",
    "jockey",
    "trainer",
    "owner",
    "breeder",
    "sire",
    "dam_sire",
    "running_style",
]

TARGET_COLUMNS = [
    "is_win",
    "is_place",
    "finish_position",
    "payout_win",
    "payout_place",
    "payout_quinella",
    "payout_wide",
    "payout_exacta",
    "payout_trio",
    "payout_trifecta",
]
