NUMERIC_FEATURES = [
    "speed",
    "stamina",
    "pace",
    "condition",
    "runner_number",
    "bracket",
    "field_size",
    "market_odds",
    "market_win_probability",
    "market_place_probability",
    "place_odds",
    "carried_weight",
    "horse_weight",
    "horse_weight_diff",
    "distance",
    "age",
    "days_since_last_run",
    "avg_last3_speed",
    "best_time",
    "last600m",
    "jockey_win_rate",
    "trainer_win_rate",
    "horse_recent_win_rate",
    "horse_recent_place_rate",
    "horse_recent_win_rate_5",
    "horse_recent_place_rate_5",
    "horse_avg_finish_last3",
    "horse_avg_finish_last5",
    "horse_win_rate_lifetime",
    "horse_place_rate_lifetime",
    "horse_avg_odds_rank_last3",
    "horse_avg_odds_last3",
    "horse_distance_place_rate",
    "horse_surface_place_rate",
    "horse_weight_change_from_last",
    "horse_weight_change_rate",
    "distance_change",
    "distance_abs_change",
    "surface_switch",
    "jockey_switch",
    "carried_weight_change",
    "jockey_recent_win_rate_50",
    "jockey_recent_place_rate_50",
    "trainer_recent_win_rate_50",
    "trainer_recent_place_rate_50",
    "horse_jockey_win_rate",
    "horse_jockey_place_rate",
    "jockey_trainer_win_rate",
    "jockey_trainer_place_rate",
    "sire_win_rate",
    "sire_place_rate",
    "dam_sire_win_rate",
    "dam_sire_place_rate",
    "sire_surface_place_rate",
    "dam_sire_surface_place_rate",
    "sire_distance_place_rate",
    "dam_sire_distance_place_rate",
    "training_score",
    "bloodline_score",
    "paddock_score",
    "lap_3f",
    "lap_4f",
    "odds_delta_5m",
    "odds_delta_15m",
    "odds_volatility",
    "body_weight_announced_minutes",
    "day_prev_races",
    "day_prev_upset_rate",
    "day_prev_favorite_win_rate",
    "day_prev_winner_avg_odds",
    "venue_day_prev_races",
    "venue_day_prev_upset_rate",
    "venue_day_prev_favorite_win_rate",
    "odds_rank",
    "odds_delta",
    "log_market_odds",
    "odds_to_favorite",
    "favorite_market_odds",
    "market_top3_probability",
    "market_entropy",
    "market_rank_pct",
    "carried_weight_vs_field",
    "horse_weight_vs_field",
    "age_vs_field",
    "rest_vs_field",
    "avg_speed_vs_field",
    "recent_place_vs_field",
    "jockey_win_vs_field",
    "trainer_win_vs_field",
    "draw_bias_vs_field",
    "ticket_pool_share",
    "draw_bias",
]

CATEGORICAL_FEATURES = [
    "venue",
    "surface",
    "going",
    "weather",
    "sex",
    "jockey",
    "trainer",
    "owner",
    "breeder",
    "sire_id",
    "sire",
    "dam_sire_id",
    "dam_sire",
    "running_style",
]

TARGET_COLUMNS = [
    "is_win",
    "is_place",
    "finish_position",
    "payout_win",
    "payout_place",
    "payout_quinella",
    "payout_wide",
    "payout_exacta",
    "payout_trio",
    "payout_trifecta",
]

UNSAFE_TRAINING_FEATURES = {
    # These are heuristic UI/model inputs unless backed by a verifiable source.
    "speed",
    "stamina",
    "pace",
    "condition",
    "training_score",
    "bloodline_score",
    "paddock_score",
    # The current local converter maps this source column to a value that is
    # often larger than win odds, so it is not reliable as a pre-race feature.
    "place_odds",
    # These are race-result values in the local keiba_data export. They can be
    # used only after shifting into historical aggregates.
    "best_time",
    "last600m",
}

TRAINING_NUMERIC_FEATURES = [
    column for column in NUMERIC_FEATURES if column not in UNSAFE_TRAINING_FEATURES
]
